config/routes.rb
Rails.application.routes.draw do
    

    mount RedactorRails::Engine => '/redactor_rails'
    resources :user_sessions, only: [:create, :new, :destroy]
  
    get 'admin', to: 'dashboard#index', as: '/'
    get 'customers/services' => 'customers#services'
    get 'customers/courses' => 'customers#courses'
    get 'types/:slug/jobs' => 'types#jobs'
    get 'courses/:slug/courses' => 'coursess#courses'
    get 'modalities/courses' => 'modalities#courses'
    get 'headers/page/:page' => 'headers#page'
    get 'contacts/addnewsletter' => 'contacts#addnewsletter'
    get 'talents/categories' => 'talents#categories'
    get 'tags/:tag', to: 'posts#tags', as: :tag

    get 'members/team' => 'members#team'
    get 'courses/bymodality' => 'courses#bymodality'
    get 'courses/pagamentoretorno' => 'courses#pagamentoretorno'
    get 'classrooms/nextcourses' => 'classrooms#nextcourses'
    get 'classrooms/opened' => 'classrooms#opened'
    
    resources :subscriptions
    resources :students
    resources :headers
    resources :modalities
    resources :courses
    resources :categories
    resources :members
    resources :types
    resources :users
    resources :videos
    resources :customers
    resources :jobs
    resources :talents
    resources :services
    resources :posts
    resources :testimonies
    resources :vouchers
    resources :classrooms
    resources :boxes
    resources :user_sessions

  root to: "home#index"  

  scope '/api' do
    get 'headers/page/:page' => 'headers#page'
    get 'customers/services' => 'customers#services'
    get 'customers/courses' => 'customers#courses'
    get 'modalities/courses' => 'modalities#courses'
    get 'talents/categories' => 'talents#categories'
    get 'posts/publisheds' => 'posts#publisheds'
    get 'classrooms/nextcourses' => 'classrooms#nextcourses'
    get 'classrooms/opened' => 'classrooms#opened'
    resources :subscriptions, defaults: {format: :json}
    resources :students, defaults: {format: :json}
    resources :modalities, defaults: {format: :json}
    resources :courses, defaults: {format: :json}
    resources :classrooms, defaults: {format: :json}
    resources :headers, defaults: {format: :json}
    resources :testimonies, defaults: {format: :json}
    resources :posts, defaults: {format: :json}
    resources :categories, defaults: {format: :json}
    resources :services, defaults: {format: :json}
    resources :customers, defaults: {format: :json}
    resources :members, defaults: {format: :json}
    resources :talents, defaults: {format: :json}
    resources :jobs, defaults: {format: :json}
    resources :videos, defaults: {format: :json}
    resources :types, defaults: {format: :json}    
  end

end

app/models/box.rb
class Box < ActiveRecord::Base
	IMAGES_SIZES = {
		:default => [1900, 450],
		:thumb => [1900, 450],		
	}
	mount_uploader :image, PictureUploader
	mount_uploader :video, MovieUploader do
    def url(format = nil)
      uploaded_path = encode_path(file.path.sub(File.expand_path(root), ''))
      return uploaded_path if format.nil?
      files = Dir.entries(File.dirname(file.path))
      files.each do |f|
        next unless File.extname(f) == '.' + format.to_s
        return File.dirname(uploaded_path) + '/' + f
      end
    end
  end
end

app/controllers/admin/boxes_controller.rb
class Admin::BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
  end

  # GET /boxes/new
  def new
    @box = Box.new
    @pages = ['a-empresa', 'cursos', 'quem-atendemos', 'blog', 'contato', 'servicos', 'depoimentos', 'cases', 'banco-de-talentos']
  end

  # GET /boxes/1/edit
  def edit
    @pages = ['a-empresa', 'cursos', 'quem-atendemos', 'blog', 'contato', 'servicos', 'depoimentos', 'cases', 'banco-de-talentos']
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:title, :body, :image, :video, :page)
    end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]
  #before_action :require_authentication, only: [:create, :new, :edit, :update, :destroy]

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
  end

  # GET /boxes/new
  def new
    @box = Box.new
    @pages = ['a-empresa', 'cursos', 'quem-atendemos', 'blog', 'contato', 'servicos', 'depoimentos', 'cases', 'banco-de-talentos']
  end

  # GET /boxes/1/edit
  def edit
    @pages = ['a-empresa', 'cursos', 'quem-atendemos', 'blog', 'contato', 'servicos', 'depoimentos', 'cases', 'banco-de-talentos']
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:title, :body, :image, :video, :page)
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.erb
<%= bootstrap_form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.text_area :body, :class => 'redactor' %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.file_field :video %>
  </div>
  <div class="field">
    <%= f.select :page, options_for_select(@pages), :prompt => 'Selecione' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<h1>Listing boxes</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Image</th>
      <th>Video</th>
      <th>Page</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boxes.each do |box| %>
      <tr>
        <td><%= box.title %></td>
        <td><%= box.body %></td>
        <td><%= box.image %></td>
        <td><%= box.video %></td>
        <td><%= box.page %></td>
        <td><%= link_to 'Show', box %></td>
        <td><%= link_to 'Edit', edit_box_path(box) %></td>
        <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Box', new_box_path %>

app/views/boxes/new.html.erb
<h1>New box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @box.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @box.body %>
</p>

<p>
  <strong>Image:</strong>
  <%= @box.image %>
</p>

<p>
  <strong>Video:</strong>
  <%= @box.video %>
</p>

<p>
  <strong>Page:</strong>
  <%= @box.page %>
</p>

<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>