config/routes.rb
Rails.application.routes.draw do
    

    mount RedactorRails::Engine => '/redactor_rails'
    resources :user_sessions, only: [:create, :new, :destroy]
  
    get 'admin', to: 'dashboard#index', as: '/'
    get 'customers/services' => 'customers#services'
    get 'customers/courses' => 'customers#courses'
    get 'types/:slug/jobs' => 'types#jobs'
    get 'courses/:slug/courses' => 'coursess#courses'
    get 'modalities/courses' => 'modalities#courses'
    get 'headers/page/:page' => 'headers#page'
    get 'contacts/addnewsletter' => 'contacts#addnewsletter'
    get 'talents/categories' => 'talents#categories'
    get 'tags/:tag', to: 'posts#tags', as: :tag

    get 'members/team' => 'members#team'
    get 'courses/bymodality' => 'courses#bymodality'
    get 'courses/pagamentoretorno' => 'courses#pagamentoretorno'
    get 'classrooms/nextcourses' => 'classrooms#nextcourses'
    get 'classrooms/opened' => 'classrooms#opened'
    
    resources :subscriptions
    resources :students
    resources :headers
    resources :modalities
    resources :courses
    resources :categories
    resources :members
    resources :types
    resources :users
    resources :videos
    resources :customers
    resources :jobs
    resources :talents
    resources :services
    resources :posts
    resources :testimonies
    resources :vouchers
    resources :classrooms
    resources :boxes
    resources :user_sessions

  root to: "home#index"  

  scope '/api' do
    get 'headers/page/:page' => 'headers#page'
    get 'customers/services' => 'customers#services'
    get 'customers/courses' => 'customers#courses'
    get 'modalities/courses' => 'modalities#courses'
    get 'talents/categories' => 'talents#categories'
    get 'posts/publisheds' => 'posts#publisheds'
    get 'classrooms/nextcourses' => 'classrooms#nextcourses'
    get 'classrooms/opened' => 'classrooms#opened'
    resources :subscriptions, defaults: {format: :json}
    resources :students, defaults: {format: :json}
    resources :modalities, defaults: {format: :json}
    resources :courses, defaults: {format: :json}
    resources :classrooms, defaults: {format: :json}
    resources :headers, defaults: {format: :json}
    resources :testimonies, defaults: {format: :json}
    resources :posts, defaults: {format: :json}
    resources :categories, defaults: {format: :json}
    resources :services, defaults: {format: :json}
    resources :customers, defaults: {format: :json}
    resources :members, defaults: {format: :json}
    resources :talents, defaults: {format: :json}
    resources :jobs, defaults: {format: :json}
    resources :videos, defaults: {format: :json}
    resources :types, defaults: {format: :json}    
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
	extend FriendlyId
	IMAGE_SIZES = {
		:default 	=> [500, 500],
		:header 	=> [770, 485],
		:thumb 		=> [270, 170],
		:mini 		=> [80, 80]
	}
	mount_uploader :image, PictureUploader

	belongs_to :type

	validates_presence_of :title	
	validates_presence_of :type_id	
	validates_presence_of :slug

	scope :most_recent, -> {order('created_at DESC')}

	friendly_id :title, use: [:slugged, :history]	

	def self.search(query)
		if query.present?
			where(['title LIKE :query OR client LIKE :query', query: '%#{query}%'])
		else
			Job.all.all
		end
	end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @search_query = params[:q]
    jobs = Job.search(@search_query)
    @jobs = jobs.most_recent.map do |job|
      JobPresenter.new(job)
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    job_model = Job.friendly.find(params[:id])
    @job = JobPresenter.new(job_model)
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :type_id, :image, :video, :client, :need, :solution, :result, :technical_form)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  #before_action :require_authentication, only: [:create, :new, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @search_query = params[:q]
    jobs = Job.search(@search_query)
    @jobs = jobs.most_recent.map do |job|
      JobPresenter.new(job)
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    job_model = Job.friendly.find(params[:id])
    @job = JobPresenter.new(job_model)
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :type_id, :image, :video, :client, :need, :solution, :result, :technical_form)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/jobs/_form.html.erb
<%= bootstrap_form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.select :type_id, Type.all.collect {|x| [x.title, x.id]}, :prompt => 'Selecione o tipo de trabalho' %>
  </div>
  <div class="field">    
    <%= f.text_field :title %>
  </div>
  <div class="field">    
    <%= f.file_field :image %>
  </div>
  <div class="field">    
    <%= f.text_field :video %>
  </div>
  <div class="field">    
    <%= f.text_field :client %>
  </div>
  <div class="field">    
    <%= f.text_area :need, :class => 'redactor', :rows => 100, :cols => 120 %>
  </div>
  <div class="field">    
    <%= f.text_area :solution, :class => 'redactor', :rows => 100, :cols => 120 %>
  </div>
  <div class="field">    
    <%= f.text_area :result, :class => 'redactor', :rows => 100, :cols => 120 %>
  </div>
  <div class="field">
    <%= f.text_area :technical_form, :class => 'redactor', :rows => 100, :cols => 120 %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary pull-right' %>
  </div>
<% end %>
<br><br><br><br>

app/views/admin/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>
<br><br><br><br>
<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/admin/jobs/index.html.erb
<h1><%= t('.page_title') %></h1>
<div class="row">
<%= link_to t('.new'), new_job_path, class: 'btn btn-default pull-right' %>
</div>
<br>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= t('.title') %></th>
      <th><%= t('.type') %></th>
      <th><%= t('.client') %></th>
      <th><%= t('.need') %></th>
      <th><%= t('.solution') %></th>
      <th><%= t('.result') %></th>
      <th><%= t('.technical_form') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.type %></td>
        <td><%= job.client %></td>
        <td><%= truncate(job.need, length: 45, escape: false) %></td>
        <td><%= truncate(job.solution, length: 45, escape: false) %></td>
        <td><%= truncate(job.result, length: 45, escape: false) %></td>
        <td><%= truncate(job.technical_form, length: 45, escape: false) %></td>
        <td><%= link_to t('links.show'), job, class: 'btn btn-xs btn-primary' %></td>
        <td><%= link_to t('links.edit'), edit_job_path(job), class: 'btn btn-xs btn-success' %></td>
        <td><%= link_to t('links.destroy'), job, class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/jobs/new.html.erb
<h1><%= t('.page_title') %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), jobs_path %>

app/views/admin/jobs/show.html.erb
<p id="notice" class="alert"><%= notice %></p>

<p>
  <strong><%= t('.title') %>:</strong>
  <%= @job.title %>
</p>

<p>
  <%= @job.show_image %>
</p>

<p>
  <strong><%= t('.client') %>:</strong>
  <%= @job.client %>
</p>

<p>
  <strong><%= t('.need') %>:</strong>
  <%= @job.need %>
</p>

<p>
  <strong><%= t('.solution') %>:</strong>
  <%= @job.solution %>
</p>

<p>
  <strong><%= t('.result') %>:</strong>
  <%= @job.result %>
</p>

<p>
  <strong><%= t('.technical_form') %>:</strong>
  <%= @job.technical_form %>
</p>

<%= link_to t('links.edit'), edit_job_path(@job) %> |
<%= link_to t('links.back'), jobs_path %>