config/routes.rb
Rails.application.routes.draw do
    

    mount RedactorRails::Engine => '/redactor_rails'
    resources :user_sessions, only: [:create, :new, :destroy]
  
    get 'admin', to: 'dashboard#index', as: '/'
    get 'customers/services' => 'customers#services'
    get 'customers/courses' => 'customers#courses'
    get 'types/:slug/jobs' => 'types#jobs'
    get 'courses/:slug/courses' => 'coursess#courses'
    get 'modalities/courses' => 'modalities#courses'
    get 'headers/page/:page' => 'headers#page'
    get 'contacts/addnewsletter' => 'contacts#addnewsletter'
    get 'talents/categories' => 'talents#categories'
    get 'tags/:tag', to: 'posts#tags', as: :tag

    get 'members/team' => 'members#team'
    get 'courses/bymodality' => 'courses#bymodality'
    get 'courses/pagamentoretorno' => 'courses#pagamentoretorno'
    get 'classrooms/nextcourses' => 'classrooms#nextcourses'
    get 'classrooms/opened' => 'classrooms#opened'
    
    resources :subscriptions
    resources :students
    resources :headers
    resources :modalities
    resources :courses
    resources :categories
    resources :members
    resources :types
    resources :users
    resources :videos
    resources :customers
    resources :jobs
    resources :talents
    resources :services
    resources :posts
    resources :testimonies
    resources :vouchers
    resources :classrooms
    resources :boxes
    resources :user_sessions

  root to: "home#index"  

  scope '/api' do
    get 'headers/page/:page' => 'headers#page'
    get 'customers/services' => 'customers#services'
    get 'customers/courses' => 'customers#courses'
    get 'modalities/courses' => 'modalities#courses'
    get 'talents/categories' => 'talents#categories'
    get 'posts/publisheds' => 'posts#publisheds'
    get 'classrooms/nextcourses' => 'classrooms#nextcourses'
    get 'classrooms/opened' => 'classrooms#opened'
    resources :subscriptions, defaults: {format: :json}
    resources :students, defaults: {format: :json}
    resources :modalities, defaults: {format: :json}
    resources :courses, defaults: {format: :json}
    resources :classrooms, defaults: {format: :json}
    resources :headers, defaults: {format: :json}
    resources :testimonies, defaults: {format: :json}
    resources :posts, defaults: {format: :json}
    resources :categories, defaults: {format: :json}
    resources :services, defaults: {format: :json}
    resources :customers, defaults: {format: :json}
    resources :members, defaults: {format: :json}
    resources :talents, defaults: {format: :json}
    resources :jobs, defaults: {format: :json}
    resources :videos, defaults: {format: :json}
    resources :types, defaults: {format: :json}    
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :classroom
  belongs_to :student
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:classroom_id, :student_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :classroom_id %><br>
    <%= f.text_field :classroom_id %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.text_field :student_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Classroom</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.classroom %></td>
        <td><%= subscription.student %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Classroom:</strong>
  <%= @subscription.classroom %>
</p>

<p>
  <strong>Student:</strong>
  <%= @subscription.student %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>